name: learn-github
run-name: ${{github.actor}} is run name
on:
  - push
jobs:
  check-bat-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install -g bats
      - run: bats -v
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: install node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: install packet from package.json
        run: npm install

